// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCynqHjYhbRwSDMVtreM6W1K6iLKBQiCQk',
    appId: '1:558530618886:web:549859bf9849116d5d8587',
    messagingSenderId: '558530618886',
    projectId: 'visualiza-preco-app',
    authDomain: 'visualiza-preco-app.firebaseapp.com',
    storageBucket: 'visualiza-preco-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa5YqtdyMdVMyoYX-WQltJxfG-Qwz5hhU',
    appId: '1:558530618886:android:86c0444650ba0c995d8587',
    messagingSenderId: '558530618886',
    projectId: 'visualiza-preco-app',
    storageBucket: 'visualiza-preco-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDadddYro4QAqwWHEQ1Lb4wlRbe95YiZ3g',
    appId: '1:558530618886:ios:f7301ecc41bec7bb5d8587',
    messagingSenderId: '558530618886',
    projectId: 'visualiza-preco-app',
    storageBucket: 'visualiza-preco-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterVisualizadorDePrecos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDadddYro4QAqwWHEQ1Lb4wlRbe95YiZ3g',
    appId: '1:558530618886:ios:f7301ecc41bec7bb5d8587',
    messagingSenderId: '558530618886',
    projectId: 'visualiza-preco-app',
    storageBucket: 'visualiza-preco-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterVisualizadorDePrecos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCynqHjYhbRwSDMVtreM6W1K6iLKBQiCQk',
    appId: '1:558530618886:web:4b179ddc1c2983a95d8587',
    messagingSenderId: '558530618886',
    projectId: 'visualiza-preco-app',
    authDomain: 'visualiza-preco-app.firebaseapp.com',
    storageBucket: 'visualiza-preco-app.firebasestorage.app',
  );
}
